### ISSUE TITLE
Code Review Request

### ISSUE THREAD

**Issue by caglabalcik** [bounswe/bounswe2015group1#121]
Hey peers, I'd be glad getting your feedback about these commits:
https://github.com/bounswe/bounswe2015group1/commit/5be3c39b43a58d7f164a3b449d5cd9b2741bfef0
https://github.com/bounswe/bounswe2015group1/commit/9d8180ee99d139b5d9764b7173f8c4042943c8da
https://github.com/bounswe/bounswe2015group1/commit/9f26af17c154c28cc2d8e9c6a4d43fffe21ea948
and more if you wish :8ball:

**Comment by caglabalcik** [comment]
There you go! @kerata :+1:

**Comment by kerata** [comment]
**Clarity**
 * Code seems to be pretty clear since variable and method names, indentations and code style is accurate and methods are short.
 * Also methods extensively make use of pretty powerful library called Gson and another class named GeneralRequest<?>, hance it does not require much of comments. But since methods are public, one sentence definition of method would have been helpful and also required for documentation, even though method names are pretty clear.

**Tests**
 * There are no unit tests for these methods. Our latency limit determined in requirement analysis is 1 second. So calling these methods and checking accuracy of results, also expecting the result under 1 second would create unit test for each methods since these are API call implementations on Android Application.

**Comment by caglabalcik** [comment]
Thanks for review @kerata :+1:
