### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by grkmndr** [bounswe/bounswe2015group1#124]
Please review the following commit of mine: https://github.com/bounswe/bounswe2015group1/commit/24a1103e2beda4500648c1612eeef69b2f12244b

**Comment by caglabalcik** [comment]
With pleasure :+1:

**Comment by caglabalcik** [comment]
Hey Görkem, I see that you put in a good effort on our project which I was aware before reviewing your commits already. Aside of this commit that I’m reviewing, thank you for the concurrent tests that you are implementing along the project. I will try to keep up! In this commit you contributed well.

Code clarity
Good. Reading the code and understanding is nonproblematic however I suggest you to do more detailed heading(description) for your commit. Instead of “New API calls are implemented”, you can specify as for example “Average rating and User Rating API calls are implemented.” That would give me an up-front idea about your code.

Bugs.
Adding the JSON string in the XML file does not work as expected. The XML is not able to parse the white spaces correctly.

Missing Features
There is no missing features, the opposite way round you deleted and fixed the code nicely as far as I see. Good job!

Coding convention:
Variable names you used reduces the effort needed to read and understand your code and enhances the code appearance since the variables are short but meaningful.
Indentation is very good.
You can try commenting more often. Yet, I can not blame you that I don’t see your point. 
Incomplete Code Documentation
Yes. Code documentation is needed.

Coverage with unit tests?
Test are done. Test datas exist. Good job!

I think that I  can modify the code easil. I can add test datas to this commit easily. I can add a new comment c5 of for example Onur Musaoğlu and added that to the cArray.

My opinion about the style used in constructs (e.g., classes, loops, methods, etc.) that it is performed well. All is readable and well implemented. However, I’m adding specific notes on github to your commit you can check.
IntelliJ Code Analyzer points out that the code runs perfectly. Good job Görkem!

**Comment by grkmndr** [comment]
Thank you so much for this great review !
