### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by sleepnir** [bounswe/bounswe2015group1#125]
Please review my code. https://github.com/bounswe/bounswe2015group1/commit/afbfa619a50507fee6c977ec423fc56230c37913 #review4review

**Comment by grkmndr** [comment]
Gotcha !

**Comment by grkmndr** [comment]
In this commit, the code is pretty clear and also the indentation and the variable names are proper. However there are no comments or a code documentation but I don't think that anyone does that in our group anyways. As far as I can tell there are no bugs regarding this commit but one thing I can suggest is using the UNIX timestamp for getting the date related variables. You can achieve this by using the following code piece;
var date = new Date(unix_timestamp*1000);
Then you can get the current hour by using date.getHours and the current minute by using date.getMinutes and so on.

The code is well constructed in general and I think you did a pretty good job !

**Comment by onurmus** [comment]
Hello. Firstly it will be proper to say that your code contains some commented codes which is not used. For the sake of readability you can remove these parts from your code. Also when I read your code I see some variable names which are not explanatory like "max". Moreover, to understand your code, I have to follow the code because you did not comment your code properly. 
Also, for debugging code you use mostly console.log() with object together with string like in line78 in viewMenuCtrl.js. these cause not to see deep inside of objects. if you want to see object with its fields you should log them without concatenating strings. Moreover for some parts of your api calls you did not catch the exceptions. this can be a problem for usability of our site. you should catch the exceptions and give information to user for satisfaction of usage.

To control your code I use http://www.jslint.com/ which is checkstyle like tool for js, and it gives some errors. For the style of your code you can use that one too.

However, I like your code organization. By just reading your code without comments I understood the code. You divide your code in proper pieces and this make me happy when I try to change some parts of your code. 

Respect

**Comment by sleepnir** [comment]
Thanks a lot to both of you. I will try to fix the problems considering your suggestions.
