### ISSUE TITLE
Please review my code

### ISSUE THREAD

**Issue by onurmus** [bounswe/bounswe2015group1#127]
please review my code for commit https://github.com/bounswe/bounswe2015group1/commit/0f356620b844eacabdbef1cb70cb77fabdb103ec

**Comment by sleepnir** [comment]
Code and commit itself are self explanatory; but, even though it applies to me and everyone in our group, a little bit comment would be cool. Since I am also involved with this part and the commit itself is about separating the controllers, there was no known bugs in this commit. The separation of controllers was a neat idea.

The code related to this commit doesn't include tests; but, in the later ones, a module for testing the code is added as all of us know. So, there is no need to add tests. The coding convention is the defacto convention that we use for frontend part in the project.

Also, I run JSHint tool for code analysis. Since, in this commit controllers are separated, I run the tool on previous unseparated file which includes the same code for ease of test. It didn't gave any warning except forgotten semicolons which do not pose serious problems.

My suggestion would be that instead of using a service call and watching another variable to check the result of the call from the service again, using services to call and making the caller to use the returned promise object. However, in the later version, we switched to this method; so, you don't need to make any changes.

Good job.

**Comment by onurmus** [comment]
you are the best, thank you
